language: java
jdk:
  - openjdk11
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jdk
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: "jamhaven"
    token:
      secure: "bcdb99736eef8a1a6185c1820d19553c8f28e81e" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=JamHaven_snek